<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-ALIGVLK" name="ee.protoskoop.gwt.edulog.TeacherTest" tests="6" failures="0" timestamp="2021-02-09T18:07:30 EET" time="4.338" errors="1">
  <testcase name="studyGroupTableIsPopulated" time="0.092" classname="ee.protoskoop.gwt.edulog.TeacherTest"/>
  <system-out/>
  <testcase name="sessionsAreStoredInDatabase" time="4.039" classname="ee.protoskoop.gwt.edulog.TeacherTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at ee.protoskoop.gwt.edulog.server.DAO.addSessionsToDatabase(DAO.java:278)
at ee.protoskoop.gwt.edulog.TeacherTest.sessionsAreStoredInDatabase(TeacherTest.java:84)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- sessionsAreStoredInDatabase -->
  <system-out/>
  <testcase name="subjectsAreStoredInDatabase" time="0.016" classname="ee.protoskoop.gwt.edulog.TeacherTest"/>
  <system-out/>
  <testcase name="sessionsAreStoredLocally" time="0.015" classname="ee.protoskoop.gwt.edulog.TeacherTest"/>
  <system-out/>
  <testcase name="subjectTableIsPopulated" time="0.013" classname="ee.protoskoop.gwt.edulog.TeacherTest"/>
  <system-out/>
  <testcase name="studyGroupsAreStoredInDatabase" time="0.163" classname="ee.protoskoop.gwt.edulog.TeacherTest"/>
  <system-out/>
</testsuite> <!-- ee.protoskoop.gwt.edulog.TeacherTest -->
